name: Generate Datas

on:
  schedule: # execute every 5 minuts
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ErlonLy
          svg_out_path:  dist/github-snake.svg, dist/github-snake-dark.svg?palette=github-dark,  dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
          
      - uses: Platane/snk/svg-only@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
